-- Database schema for Marketplace Bidding System (PostgreSQL)
-- This script was generated by the ERD tool in pgAdmin 4.

BEGIN;

CREATE TABLE IF NOT EXISTS public.auctions
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    category character varying(20) COLLATE pg_catalog."default" DEFAULT 'others'::character varying,
    starting_price numeric(10, 2) NOT NULL,
    current_price numeric(10, 2) DEFAULT 0.00,
    buy_now_price numeric(10, 2) DEFAULT NULL::numeric,
    location character varying(100) COLLATE pg_catalog."default",
    image_url character varying(500) COLLATE pg_catalog."default",
    start_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    end_time timestamp without time zone NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'active'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT auctions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bids
(
    id serial NOT NULL,
    auction_id integer NOT NULL,
    user_id integer NOT NULL,
    bid_amount numeric(10, 2) NOT NULL,
    bid_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bids_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS public.auctions
    ADD CONSTRAINT auctions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_auctions_user_id
    ON public.auctions(user_id);

ALTER TABLE IF EXISTS public.bids
    ADD CONSTRAINT bids_auction_id_fkey FOREIGN KEY (auction_id)
    REFERENCES public.auctions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_bids_auction_id
    ON public.bids(auction_id);

ALTER TABLE IF EXISTS public.bids
    ADD CONSTRAINT bids_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_bids_user_id
    ON public.bids(user_id);

-- Insert sample data
INSERT INTO users (username, email, password) VALUES
('demo_user', 'demo@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'), -- password: password
('test_seller', 'seller@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi') -- password: password
ON CONFLICT (username) DO NOTHING;

INSERT INTO auctions (user_id, title, description, category, starting_price, current_price, buy_now_price, location, image_url, end_time) VALUES
(1, 'iPhone 14 Pro', 'Excellent condition iPhone 14 Pro, 256GB, Space Black. Includes original box and charger.', 'electronics', 800.00, 850.00, 1200.00, 'София', 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=500', CURRENT_TIMESTAMP + INTERVAL '2 days'),
(2, 'Vintage Leather Jacket', 'Genuine leather jacket from the 80s, size M. Great condition, no damages.', 'fashion', 50.00, 75.00, 150.00, 'Пловдив', 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500', CURRENT_TIMESTAMP + INTERVAL '1 day'),
(1, 'Gaming Chair', 'Ergonomic gaming chair with lumbar support. Used for 6 months, like new condition.', 'home', 100.00, 120.00, 250.00, 'Варна', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500', CURRENT_TIMESTAMP + INTERVAL '3 days'),
(2, 'MacBook Air M1', '2021 MacBook Air with M1 chip, 8GB RAM, 256GB SSD. Perfect working condition.', 'electronics', 700.00, 750.00, 1000.00, 'София', 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500', CURRENT_TIMESTAMP + INTERVAL '4 days'),
(1, 'Nike Running Shoes', 'Brand new Nike Air Max, size 42, never worn. Original packaging included.', 'sports', 80.00, 80.00, 140.00, 'Бургас', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500', CURRENT_TIMESTAMP + INTERVAL '5 days')
ON CONFLICT DO NOTHING;

INSERT INTO bids (auction_id, user_id, bid_amount) VALUES
(1, 2, 820.00),
(1, 1, 850.00),
(2, 1, 60.00),
(2, 2, 75.00),
(3, 2, 110.00),
(3, 1, 120.00),
(4, 1, 720.00),
(4, 2, 750.00)
ON CONFLICT DO NOTHING;

END;